/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KenyaRouteImport } from './routes/kenya'
import { Route as SouthSudanRouteImport } from './routes/south-sudan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KenyaRoute = KenyaRouteImport.update({
  id: '/kenya',
  path: '/kenya',
  getParentRoute: () => rootRouteImport,
} as any)
const SouthSudanRoute = SouthSudanRouteImport.update({
  id: '/south-sudan',
  path: '/south-sudan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kenya': typeof KenyaRoute
  '/south-sudan': typeof SouthSudanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kenya': typeof KenyaRoute
  '/south-sudan': typeof SouthSudanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kenya': typeof KenyaRoute
  '/south-sudan': typeof SouthSudanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kenya' | '/south-sudan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kenya' | '/south-sudan'
  id: '__root__' | '/' | '/kenya' | '/south-sudan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KenyaRoute: typeof KenyaRoute
  SouthSudanRoute: typeof SouthSudanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kenya': {
      id: '/kenya'
      path: '/kenya'
      fullPath: '/kenya'
      preLoaderRoute: typeof KenyaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/south-sudan': {
      id: '/south-sudan'
      path: '/south-sudan'
      fullPath: '/south-sudan'
      preLoaderRoute: typeof SouthSudanRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KenyaRoute: KenyaRoute,
  SouthSudanRoute: SouthSudanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
